# This service setup creates a Postgres database, applies the initialization scripts
# (config/*.sql) and starts the Go application in another container.
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      # Avoiding port conflicts with other local Postgres instances.
      - "5434:5432"
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb && psql -U postgres -d mydb -c 'SELECT COUNT(*) FROM assets_org_111111111111;' > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  app:
    image: golang:trixie
    container_name: golang_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8110:8110" # http://localhost:8110/ask or /mcp
    env_file:
      - .app.env
    command: go run .
    depends_on:
      postgres:
        condition: service_healthy
